# **SIN-393 - Introduction to Computer Vision (2023-2)**

# Lecture 03 - Introduction to NumPy

Prof. João Fernando Mari ([*joaofmari.github.io*](https://joaofmari.github.io/))

---

* Material based on **Scipy Lecture Notes**.
     * Available at: http://www.scipy-lectures.org/

## Importing NumPy
---
* Import conventions.
    * NumPy documentation:
        * http://docs.scipy.org/

In [1]:
import numpy as np

## NumPy arrays
---
* Arranjos NumPy são containers que fornecem operações numéricas rápidas e uso eficiente da memória.

In [2]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

* Computing the square of a sequence of 1000 integers using Python lists.

In [3]:
# Uma lista com 1000 números inteiros
L = range(1000)

%timeit [i**2 for i in L]

618 µs ± 70.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


* Computing the square of a sequence of 1000 integers using NumPy arrays.

In [4]:
# Arranjo NumPy com 1000 números
a = np.arange(1000)
%timeit a**2

2.73 µs ± 341 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Creating NumPy arrays
---

### Creating arrays manually

* 1D arrays

In [5]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [6]:
print(a)
print(type(a))
print(len(a))      
print(a.ndim)
print(a.shape)

[0 1 2 3]
<class 'numpy.ndarray'>
4
1
(4,)


* 2D arrays

In [7]:
b = np.array([[0, 1, 2], 
              [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
print(b)
print(type(b))
print(len(b))      
print(b.ndim)
print(b.shape)

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>
2
2
(2, 3)


* 3D arrays

In [9]:
c = np.array([[[1,  2,  3,  1],
               [4,  5,  6,  5],
               [7,  8,  9,  9]],
              [[10, 11, 12, 10],
               [13, 14, 15, 14],
               [16, 17, 18, 18]]])
c

array([[[ 1,  2,  3,  1],
        [ 4,  5,  6,  5],
        [ 7,  8,  9,  9]],

       [[10, 11, 12, 10],
        [13, 14, 15, 14],
        [16, 17, 18, 18]]])

In [10]:
print(c)
print(type(c))
print(len(c))      
print(c.ndim)
print(c.shape)

[[[ 1  2  3  1]
  [ 4  5  6  5]
  [ 7  8  9  9]]

 [[10 11 12 10]
  [13 14 15 14]
  [16 17 18 18]]]
<class 'numpy.ndarray'>
2
3
(2, 3, 4)


### Functions for creating arrays

* In practice, arrays are rarely created manually.

* Equaly spaced arrays

In [11]:
a = np.arange(10) # 0 .. n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(1, 9, 2)
b

array([1, 3, 5, 7])

* By number of points.
     * Syntax: ```np.linspace(ini_val, end_val, num_points)```
         - ```ini_val```: initial value;
         - ```end_val```: final value;
         - ```num_points```: number of points.

In [13]:
c = np.linspace(0, 1, 6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

### Common arrays

In [15]:
a = np.ones((3,3)) # (3, 3) é uma tupla
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [17]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

* Random numbers

In [19]:
a = np.random.rand(4) # distribuição uniforme
a

array([0.23643818, 0.47396574, 0.05731461, 0.64117828])

In [20]:
b = np.random.randn(4) # distribuição gaussiana
b

array([-0.43146091, -0.24183331,  0.33740546,  0.20333382])

In [21]:
np.random.seed(1234) # define a semente para geração dos números aleatórios

## Array data types
---

* The default data type of numpy is float64

In [22]:
c = np.ones((3, 3))
c.dtype

dtype('float64')

* When the array is created from directly, the type is inferred from the data.

In [23]:
c = np.array([1, 2, 3]) # inteiros (32 bits)
c.dtype

dtype('int32')

In [24]:
c = np.array([1., 2, 3]) # float (64 bits)
c.dtype

dtype('float64')

* Other data types allowed:

In [25]:
d = np.array([1+2j, 3+4j, 5+6j])
d.dtype

dtype('complex128')

In [26]:
f = np.array(['Um', 'Dois', 'Quatrocentos'])
f.dtype

dtype('<U12')

* Other data types allowed:
    * int16
    * int32
    * int64
    * uint32
    * float32
    * ...